CREATE DATABASE IF NOT EXISTS `cap`;

USE `cap`;

CREATE TABLE IF NOT EXISTS `payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_GENERAL_CI;

INSERT INTO `payments` (`id`, `description`) VALUES
	(1, 'Boleto'),
	(2, 'Cheque'),
	(3, 'Débito'),
	(4, 'Pix'),
	(5, 'Transferência'),
	(6, 'Dinheiro');

CREATE TABLE IF NOT EXISTS `situations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_GENERAL_CI;

INSERT INTO `situations` (`id`, `description`) VALUES
	(1, 'Aberto'),
	(2, 'Baixado'),
	(3, 'Excluído');

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  `email` VARCHAR(255) COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  `password` VARCHAR(255) COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) COLLATE UTF8MB4_GENERAL_CI NOT NULL,
  `value` DECIMAL(12,2) NOT NULL,
  `expiration` DATE NOT NULL,
  `user_owner` INT NOT NULL,
  `payment` INT NOT NULL,
  `situation` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_owner` (`user_owner`),
  KEY `payment` (`payment`),
  KEY `situation` (`situation`),
  CONSTRAINT `fk_user_owner` FOREIGN KEY (`user_owner`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_payment` FOREIGN KEY (`payment`) REFERENCES `payments` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_situation` FOREIGN KEY (`situation`) REFERENCES `situations` (`id`) ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_GENERAL_CI;
